### ISSUE TITLE
Plugin doesn't find tsconfig.json, leading to spew about missing imports, etc..

### ISSUE THREAD

**Issue by DanielJoyce** [db-migrate/plugin-typescript#10]
We're trying this out and it doesn't work at all. Per the docs we added the dependency and apparently its loaded by db-migrate via some dependency mechanism as the docs make no reference to a config file like Rollup uses.

So we run it, and ts-node is apparently failing to resolve the tsconfig.json file.

**Comment by wzrdtales** [comment]
Actually this plugin makes use of https://github.com/TypeStrong/ts-node I'm not an user of typescript at all. So I wont help you on any topic related to typescript itself and wont invest any time in it. For everything related to db-migrate itself I will help.

Maybe @RemyJeancolas or @westy92 can help you on that topic.

Considering the mechanism that loads plugins: they need to appear in your package.json and obviously need to be installed, that is where db-migrate gets them from.

This plugin itself is quite simple, it just hooks on the fileendings and execute `ts-node/register`, everything else is completely unrelated to db-migrate itself though. So maybe ts-node gets the CWD wrong or register just don't support the config you look for. I would suggest asking for help in their project as well. Feel free to reach out should that reach in a dead end.

**Comment by DanielJoyce** [comment]
Well your docs say this magically should just work without any further configuration. Which is obviously not the case. I've used ts-node seperately and it works fine. Something about this plugin itself is not correct.

**Comment by wzrdtales** [comment]
Then wait for @RemyJeancolas or @westy92, they probably can help you.

If you want to figure it out yourself:

https://github.com/db-migrate/plugin-typescript/blob/715efe7ef54196b82fce36fb57c48290e8dda5ff/index.js

Thats all nothing more there from the plugin side, no big magic, basically does nothing, everything else goes to the ts-node module.

**Comment by DanielJoyce** [comment]
rm -rf node_modules/db-migrate-plugin-typescript/node_modules fixed the issue

ts-node needs to be a peer-dependency, and not installed as a sub dependency

**Comment by wzrdtales** [comment]
missed also the fix tag, closed by #11
