### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by westy92** [db-migrate/plugin-typescript#4]
Please describe how to use this plugin.

**Comment by wzrdtales** [comment]
@RemyJeancolas Can you please help @westy92? Thanks :)

**Comment by westy92** [comment]
@wzrdtales @RemyJeancolas Any update on this?  I would love to start using this plugin but have no idea how.

**Comment by wzrdtales** [comment]
@westy92 So to actually use any plugin you need to use the latest db-migrate version (the one on the beta tree) and you need to have it installed in your project. Means there also must be an entry in your package.json. db-migrate will pick up on the plugin automatically if the entry in the package.json is found.

The plugin then hooks into functionality of db-migrate itself. In this case it hooks into `migrator:migration:hook:require`, which in this case requires another transpiler (typescript) and registers also a new file extension (.ts). So to use it in this case, you need to have the steps described above in place and name your migrations accordingly (ending with .ts).

Hope that helps.
