### ISSUE TITLE
Pass the repo over to someone else.

### ISSUE THREAD

**Issue by GeeWee** [db-migrate/plugin-typescript#7]
Hey.

This repo is pretty dead (Hasn't been updated for six months - sorely needs its dependencies updated. Has a pull request that's been lying around for ages.)

Is there any chance I could take over? It shouldn't require more than a few hours of work to get it working nicely.

**Comment by wzrdtales** [comment]
No...
The reason that this is an organization is, that any of the projects officially under the hands can be participated by anyone that is willing to do this. If you want to work on this please just ask if you can join the development and please consider to actually contribute something before stating something like this, b/c this is considered quite a rude behaviour.

**Comment by GeeWee** [comment]
Do apologize. I didn't realise it was part of the db-migrate organisation - I just thought someone had created it a long time ago and kind of forgotten about it.

I'd like to chip in, how would you prefer we do it? :)

**Comment by wzrdtales** [comment]
Also to add this was mainly the work of @RemyJeancolas who is still here.

And one note: I am very open to participation and contributions and if you're willing to invest time into this I do appreciate that. But I wont tolerate stuff like this, hopefully you did not wanted to express what actually was received here. Which I guess given from the communication in the issue over on the core project.

So please understand that this repo will remain here, but anyone willing to participate that gained enough trust can get into the organization and get access to this repo.

**Comment by wzrdtales** [comment]
Ok, we've written at the same time. I'm glad that I am right and you did not want to be rude, but just a tip if you want to verify if a project is still maintained, ask first before you tell someone to transfer it.

You can just go ahead and open issues with feature requests you want to discuss or directly go and create PRs. I'm fine with both though.

**Comment by GeeWee** [comment]
My bad - I gotchu.
